name: Build & Publish Notebook Server Docker images
on:
  push:
    branches:
      - master
      - v*-branch
    paths:
      - components/example-notebook-servers/jupyter-scipy/**
      - components/example-notebook-servers/jupyter/**
      - components/example-notebook-servers/base/**
      - releasing/version/VERSION
  pull_request:
    branches:
      - master
      - v*-branch
    paths:
      - components/example-notebook-servers/**

jobs:
  push_to_registry:
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          version:
            - 'releasing/version/VERSION'

    - name: Login to DockerHub
      if: github.event_name == 'push'
      uses: docker/login-action@v2
      with:
        username: kubeflownotebookswg
        password: ${{ secrets.KUBEFLOWNOTEBOOKSWG_DOCKER_TOKEN }}

    - name: Build all Notebook Server images via central-Makefile
      run: |
        cd components/example-notebook-servers/
        export TAG=$(git describe --tags --always --dirty)
        make docker-build -C jupyter-scipy TAG=${TAG}

    - name: Push Notebook Server images via their Makefile
      if: github.event_name == 'push'
      run: |
        cd components/example-notebook-servers/
        export TAG=$(git describe --tags --always --dirty)
        export REGISTRY=kubeflownotebookswg
        docker tag jupyter-scipy:${TAG} ${REGISTRY}/jupyter-scipy:${TAG}
        docker push ${REGISTRY}/jupyter-scipy:${TAG}

    - name: Push Notebook Server images via their Makefile on Version change
      id: version
      if: github.event_name == 'push' && steps.filter.outputs.version == 'true'
      run: |
        export TAG=$(cat releasing/version/VERSION)
        cd components/example-notebook-servers/
        make docker-build -C jupyter-scipy TAG=${TAG}
        export REGISTRY=kubeflownotebookswg
        docker tag jupyter-scipy:${TAG} ${REGISTRY}/jupyter-scipy:${TAG}
        docker push ${REGISTRY}/jupyter-scipy:${TAG}
